### ISSUE TITLE
Align with EPO on Concession Contract

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#100]
The Eprocurement ontology just released version 3.0.0 including the concept of Concession Contract, already present in CPSV-AP 3.0.0:
https://docs.ted.europa.eu/EPO/dev/_attachments/html_reports/release-3.0.0/ePO/index.html

This issue is to remember to align with EPO (in terms of URI, meaning, properties, etc.) if needed, within the next release

**Comment by williamverbeeck** [comment]
During the webinar on the review of CPSV-AP on the 7th of November, it was agreed to review the differences in definitions with eProcurement because the eProcurement ontology contains a URI for the same concept but with a different definition.

On the 8th of November, there was an agreement with eProcurement on the following points:
- Change the URI from cv:ConcessionContract to cv:ServiceConcessionContract so the definition in CPSV-AP is kept, stressing the importance for of concession of public services.
- Making cv:ServiceConcessionContract a subClassOf epo:ConcessionContract (now it is a subclass of epo:Contract) so it is still interoperable with eProcurement.

**Comment by EmidioStani** [comment]
This issue can be closed, it is solved in the new release: https://semiceu.github.io/CPSV-AP/releases/3.1.0/
