### ISSUE TITLE
What does "cv:OpeningHoursSpecification is aligned to schema:OpeningHoursSpecification" exactly mean?

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#109]
The usage note for [the class Opening Hours Specification](https://semiceu.github.io/CPSV-AP/releases/3.0.0/#Opening%20Hours%20Specification) (and also the RDF representation) says that "This class is aligned to Schema.org OpeningHoursSpecification class."

What does "aligned to" exactly mean? 

Does it mean: 
1. `cv:OpeningHoursSpecification owl:equivalentClass schema:OpeningHoursSpecification`, 
2. `cv:OpeningHoursSpecification rdfs:subClassOf schema:OpeningHoursSpecification`, 
3. or something else?

Could you please specify this more precisely, also using machine-readable expressions in the RDF representation? 

[At the national leve, when establishing national application profiles of CPSV-AP, we have to have a semantically/ontologically as precise as possible understanding of CPSV-AP.]

**Comment by EmidioStani** [comment]
Hello @jimjyang ,

the alignment means having the same meaning (since the class was originally coming from schema.org), so the 1st option would be used.

However, there is a proposition to change this class and use [time:TemporalEntity](https://www.w3.org/TR/owl-time/#time:TemporalEntity) since the meaning is to describe a time period (or instant) that can be easily represented with TemporalEntity. The class OpeningHoursSpecification has been critiIzed in the Core Public Event working group, see issue https://github.com/SEMICeu/Core-Public-Event-Vocabulary/issues/20, thus the proposal to change it.
The proposition will be discussed during the webinar of 27 October.

**Comment by EmidioStani** [comment]
The approach of CPSV-AP will follow issue https://github.com/SEMICeu/CPOV/issues/23 that means use time:TemporalEntity for openingHours and specialOpeningHours
