### ISSUE TITLE
RDF Schema: dct:status does not exist, adms:status yes

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#39]
In the metadata of the ontology there is:

dct:status <http://purl.org/adms/status/Completed> ;

dct:status property does not exist, it shoulld be replaced by adms:status

Furthermore the status  is incosistent with the status on Joinup (see the bottom of the page):
https://joinup.ec.europa.eu/solution/core-public-service-vocabulary-application-profile

**Comment by albeaufays** [comment]
This issue has been discussed during the [webinar of the 09 December 2020](https://joinup.ec.europa.eu/collection/catalogue-services/event/webinar-catalogue-services-annual-roadmap-and-review-cpsv-ap-spec-09122020-1400-gmt1). Given that no objections were raised when the proposed resolution to the issue was presented, the proposed change will therefore be included in the next release of CPSV-AP.

**Comment by albeaufays** [comment]
This issue has been discussed during the [webinar of the 09 December 2020](https://joinup.ec.europa.eu/collection/catalogue-services/event/webinar-catalogue-services-annual-roadmap-and-review-cpsv-ap-spec-09122020-1400-gmt1). Given that no objections were raised when the proposed resolution was presented, the change will therefore be included in the next release of CPSV-AP.

**Comment by NathanGhesq** [comment]
This change has been made in CPSV-AP 3.0, therefore this issue will be closed.
