### ISSUE TITLE
RDF Schema: add subclass relation for BusinessEvent and LifeEvent

### ISSUE THREAD

**Issue by EmidioStani** [SEMICeu/CPSV-AP#40]
In the UML class diagram the BusinessEvent and LifeEvent are depicted as sublclass of Event.

Such relation is missing in the RDF Schema.

**Comment by albeaufays** [comment]
This issue has been discussed during the [webinar of the 09 December 2020](https://joinup.ec.europa.eu/collection/catalogue-services/event/webinar-catalogue-services-annual-roadmap-and-review-cpsv-ap-spec-09122020-1400-gmt1). Given that no objections were raised when the proposed resolution to the issue was presented, the proposed change will therefore be included in the next release of CPSV-AP.

**Comment by albeaufays** [comment]
This issue has been discussed during the [webinar of the 09 December 2020](https://joinup.ec.europa.eu/collection/catalogue-services/event/webinar-catalogue-services-annual-roadmap-and-review-cpsv-ap-spec-09122020-1400-gmt1). Given that no objections were raised when the proposed resolution was presented, the change will therefore be included in the next release of CPSV-AP.

**Comment by NathanGhesq** [comment]
This change has been made in CPSV-AP 3.0, therefore this issue will be closed.
