### ISSUE TITLE
Classification of a public service

### ISSUE THREAD

**Issue by ioanano** [SEMICeu/CPSV-AP#5]
Issue raised by Makx Dekkers
- replace the type attribute level by theme to put the label in line with its definition and allow for a more thematic classification
- type: redefine Type as an attribute and refer to the classification of the SDG as a recommended top-level controlled vocabulary and remove the Cofog taxonomy as a recommended controlled vocabulary.

**Comment by ioanano** [comment]
Proposal: 

- change type by theme 
- redefine Type as an attribute,
- refer to the classification of the SDG as a recommended top-level controlled vocabulary
- remove the COFOG taxonomy as a recommended controlled vocabulary

**Comment by ioanano** [comment]
Discussion during the CPSV-AP WG Webinar of 19/03:
•	Proposal to make amendments as they are suggested by the reporter: 
	Add a "Theme" property. This would allow the adoption of a more thematic approach to classify public services. 
	Redefine the "Type" attribute. The goal is to define the "Type" attribute more broadly so that it can be used in the context of the SDG for instance. This would also include referring to the classification of the SDG as a recommended top-level vocabulary, and considering the removal of the COFOG taxonomy as a recommended controlled vocabulary. 
•	Controlled vocabularies are only suggested vocabularies, but we need common ground to make sure they are widely used.
•	The term "Theme" could be ambiguous. 
	The "Type" attribute is currently not designed so that you can match it to a specific "Theme". 
	The semantics of "Type" and "Theme" are indeed considered ambiguous by the participants in the discussion on this issue. The terminology may need to be redefined. 
	Suggestion of using "Thematic area" instead of "Theme".
•	Further debate around the issue of removing the COFOG taxonomy as a recommended controlled vocabulary: since it is simply a recommendation, it could be one of several controlled vocabularies recommended in the specification.

**Comment by anarosa-es** [comment]
I agree. "Type" means nothing and everyting, and COFOG is useless in this context, so "type" property should be removed.

"Thematic area" seems very useful in order to identify functional areas. It can be related to the [Data Theme Authotity List](http://publications.europa.eu/mdr/resource/authority/data-theme/html/data-theme-eng.html), i.e., the open data categories. Moreover, with "thematic area" property we don't need the "sector" property. 

"Sector" property is related to NACE code list, but this list is so extensive that becomes useless. With "thematic area" property, "sector" property should be removed.

In the other hand, I see other dimensions for public service classification. For exmample: service by common or specific purpose, service by addressee (citizen, enterprise or public administration), service by output type (CPSV-AP output type list seems too short) and service by territorial scope (national, regional, local, others). Should we let the classification open using skos:Collection or skos:Concept classes?

**Comment by barthelemyf** [comment]
Solution implemented:
- in CPSV-AP 2.2, the property cv:thematicArea was added, 
- the property dct:type was redefined more broadly as "_the Type of a Public Service as described in a controlled vocabulary. For indicating the Type, we are referring to the functions of government to indicate the purpose of a government activity, which the public service is intended for._"
- The current classification from the SDG is not referred in version 2.2 but there is an ongoing coordination with the SDG
- The discussion about the COFOG controlled vocabulary is available from https://github.com/catalogue-of-services-isa/CPSV-AP/issues/9
- The other dimensions mentioned by [anarosa-es](https://github.com/anarosa-es) in her last comment are valuable. During the webinar of April 2018, the following decision was taken: 

> According to the agreement of WG members, the model will be altered by adding skos:Collection and skos:Concept classes to provide for additional ways of classification. 

As a result, the two classes skos:Concept and skos:Collection have been added in the version 2.2 of the CPSV-AP.

**Comment by anarosa-es** [comment]
The problem I see is that "sector" is related to NACE codelist, i.e.,  economic activities, so the public service "getting a birth certificate" has not representation here, just like other pure administrative services.  Moreover, NACE is huge and could be quite difficult to choose the right classification for public services related to economic activities. 

I'm aware that theses are optional attributes, but I cannot see the useful of "NACE sector" when we already have "thematicArea" because I cannot find a clear response to the question: which is the advantage of having this detailed classification of economic activities over having only the simple "Data Theme" controlled vocabulary which is broader than economic activities? 

And if the detail of NACE is good for some reason then, why don't we have same detail in non-economic activities?

**Comment by pwin** [comment]
+1

**Comment by NathanGhesq** [comment]
In CPSV-AP 3.0, the controlled vocabularies discussed during the webinar of 06/04 are recommended in the usage notes of the respective properties. Additionally, alignment between the SDGR and the life/business event vocabularies is currently in progress for the thematic area.

**Comment by indiamaydesign** [comment]
@NathanGhesq was there an outcome on the alignment between SDGR and life/business event vocabularies?

**Comment by NathanGhesq** [comment]
Dear India,

The updated CPSV-AP Life/Business Events codelists (which is now aligned with the SDGR as much as possible) will be published onto the EU Vocabularies website on June 14th, 2023. 

I hope this clarifies things.
