### ISSUE TITLE
Digital aspects of public services

### ISSUE THREAD

**Issue by anarosa-es** [SEMICeu/CPSV-AP#7]
CPSV-AP does not seem to describe digital aspects of public services. For instance, a public service can offer either a downloable PDF with the application form to initiate the procedure, or a web form to apply for that initation; a public service can offer a website to the intered parties where they can check its processing status; a public service can offer the possibility of communicating with intereseted parties by digital means, or can force the use of digital communications; a public service can be fully automated or even proactive. 

In this digital escenarios, CPSV-AP should be able to describe access URLs, digital identification/signature requirements, technical requirements for digital communications, etc.

**Comment by barthelemyf** [comment]
During the webinar of April 2018, the following discussion and decision were held:
- The initial resolution proposal for this issue is not to enact any changes related to this property, as it is covered by the channel class, as well as evidence, input, etc. These classes can be used for the purposes of describing digital aspects of public services. 
- In some situations and countries, the type of evidence necessary for a public service differs depending on the channel being used. This situation might make it necessary to have an association between the evidence class and the channel class, which has already been provided in the model.
- **DECISION**: The WG agreed not to make any changes, as all the above situations can be covered by the CPSV-AP in its current version.

**Comment by anarosa-es** [comment]
Considering how the catalogue of public services model can help to provide the information mentioned in SDGR Article 10 "Quality of information on procedures", I cannot see how to obtain information about the accepted digital means of authentication, identification and signature for the procedure (article 10.1.c) or online methods of payment (article 10.1.f), among others.
