### ISSUE TITLE
Requirement vs./and Evidence

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#88]
CCCEV v.2.00: As we understand it, the central class in CCCEV is "Requirement" (which could be Criterion, InformationRequirement or Constraint) which may have supporting "Evidence" ([Requirement hasSupportingEvidence Evidence; Evidence supportsRequirement Requirement](https://semiceu.github.io/CCCEV/releases/2.00/html/overview.jpg)). 

Similarly in CPSV-AP v.3.00: The description of the class [Requirement](https://catalogue-of-services-isa.github.io/CPSV-AP/releases/3.0.0/#Requirement) in CPSV-AP v.3.00 says "Condition or prerequisite that is to be proven by Evidence", and the description of the class [Evidence](https://catalogue-of-services-isa.github.io/CPSV-AP/releases/3.0.0/#Evidence) says "... any resource that can to prove that a specific requirement is met" (BTW, there is a typo in the sentence ("can to")). 

So, 
1. Why no relations between "Requirement" and "Evidence" in CPSV-AP v.3.00? 
2. Why "Evidence" as direct input to PublicService in CPSV-AP v.3.00, not as supportingEvidence to "Requirement"? [especially when Requirement according to CCCEV could be InformationRequirement]

**Comment by EmidioStani** [comment]
Hello @jimjyang ,

1) there was no particular reason to omit it, since you requested we added it, it clutters a bit the diagram (passing through different relations) but it is still readable.

2) Historically a Public Service has input as Evidence, since version 2.0, Member States can then now see how it is better to connect either directly or indirectly via Requirement
