### ISSUE TITLE
(editorial) Link fra v.3 to v.2 of CPSV-AP, or to 404?

### ISSUE THREAD

**Issue by jimjyang** [SEMICeu/CPSV-AP#98]
E.g., when you are at [Contact point in v.3.0.0](https://semiceu.github.io/CPSV-AP/releases/3.0.0/#Contact%20Point), clicking on the clickable class name Contact Point will lead you to [v.2.00 (dated 2022-04-01) of Contact point](https://semiceu.github.io/CPOV/releases/2.00/#Contact%20Point) which at least has a differente Usage note. 

Clicking on the clickable class name Business Event, Channel, ... leads to 404.

**Comment by EmidioStani** [comment]
Hello @jimjyang,

thanks for reporting this, the 404 is a result of the migration of cpsv-ap into semic eu, thus persistent URI have now been updated (/m8g links redirect back to the HTML specification when using the browser)

For the Contact Point, it is normal, as the URI is defined in CPOV 2.0.0 thus you are redirected there. The usage note can be customized by each vocabulary but they should not be different otherwise there is a semantic problem.
